apiVersion: secrets.t-inagaki.net/v1beta1
kind: SakuraCloudSecret
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-sakuracloud-secrets
    app.kubernetes.io/managed-by: kustomize
  name: sakuracloudsecret-sample
spec:
  vaultResourceID: 0 # vault resource id
  apiKey:
    secretName: api-key
  
  name: test-yaml # secret item name
  format: yaml # or json, default json

  destinationSecretName: dest-secret

  # type is optional.
  # If omitted, the controller detects the Secret type from the generated data:
  # - ".dockerconfigjson" -> kubernetes.io/dockerconfigjson
  # - ".dockercfg"        -> kubernetes.io/dockercfg
  # - "tls.crt"+"tls.key" -> kubernetes.io/tls
  # - otherwise           -> Opaque
  # type: Opaque
